package agentcompose

import "testing"

func TestIntegrationSessionRPCBridgeWorkflow(t *testing.T) {
	testSessionRPCBridgeCallJSONSupportsAllSessionRPCs(t)
}

func TestIntegrationLoaderEngineWorkflow(t *testing.T) {
	testLoaderEngineExecuteSupportsSessionRPCBindings(t)
	testLoaderEngineExecuteSupportsAgentAndLLMBindings(t)
	testLoaderEngineExecuteSupportsCommandBindings(t)
	TestLoaderEngineJSONAndRegistrationBranches(t)
}

func TestIntegrationServiceGraphRegistersV2Routes(t *testing.T) {
	testSupportSetupRegistersServiceGraph(t)
}

func TestIntegrationWebhookWorkspaceAndLoaderWorkflow(t *testing.T) {
	testConfigStoreMigrationAndTimeParsingWorkflows(t)
	testServiceConfigAndLoaderAPIs(t)
	testServiceSessionKernelAgentAndLLMAPIs(t)
	testServiceProxyRoutesRedirectAndProxy(t)
	TestServiceProxyRoutesUseGuestHostTarget(t)
	testServiceEnsureProxyReadyStartPaths(t)
	TestJupyterTargetReachableUsesGuestHostTarget(t)
	TestSessionDriverStartSessionVMSavesRuntimeProxyState(t)
	testServiceStreamingAPIs(t)
	testRuntimeProviderSelectsConfiguredRuntime(t)
	testLLMClientGenerateHandlesSuccessAndFailures(t)
	testWebhookHandlerStoresEvent(t)
	testEventQueryHandlers(t)
	testPrepareFileWorkspaceCopiesContent(t)
	testPrepareGitWorkspaceClonesRootAndTarget(t)
	testRegisterWorkspaceRoutesUploadAndList(t)
	testLoaderManagerCollectDueScheduledRunsConsumesTimeout(t)
	testLoaderRunHostCommandPersistsShellCellArtifactsAndEvents(t)
	TestLoaderRunHostCommandPersistsDockerProxyTarget(t)
	testLoaderRunHostCommandNonZeroExitCodeDoesNotThrow(t)
	testLoaderRunHostAgentStopsSessionAfterExecution(t)
	testLoaderRunCommandNewSessionsReuseAndCleanupAtRunEnd(t)
	TestLoaderRunCommandStickySessionPersistsAcrossRunsWithTitle(t)
	testLoaderManagerRunLifecycleStateLLMAndEventDispatch(t)
	testLoaderManagerDispatchScheduledRunsAndSessionResumeBranches(t)
	testLoaderScheduleModelWorkflows(t)
	testSupportConstructorsAndHelpers(t)
	testSupportControlPlaneStartAndConfigHelpers(t)
	testSupportSetupRegistersServiceGraph(t)
	testControlPlaneHelperErrorAndParsingBranches(t)
	TestModelSessionConfigAndBusBranchCoverage(t)
	TestTopicEventModelAndStoreErrorBranches(t)
	testServiceReconcilePersistedSessionsMarksStalePendingFailed(t)
	TestServiceAndBridgeReconcileMicrosandboxRuntimeTypeBranches(t)
	testStoreAgentRunLegacyVMAndListWorkflows(t)
	testStorePersistenceErrorAndUpdateBranches(t)
	testServiceProtoConversionHelpers(t)
	testAgentRunSummariesScansAllSessions(t)
	testAgentDefinitionConfigStoreCRUDAndWorkspaceProtection(t)
	testLoaderCreateBindsAgentDefinitionProvider(t)
	testAgentDefinitionValidationAndProtoMapping(t)
	testAgentDefinitionCreateSession(t)
	testDeleteAgentDefinitionStopsSessionsAndKeepsDeletedInList(t)
	testDashboardOverviewAggregatorCountsRuns(t)
	testDashboardOverviewHubWatchInitialAndNotify(t)
	testWebhookIntegrationEventDispatchRunsMatchingLoader(t)
}

func TestE2ESessionRPCBridgeWorkflow(t *testing.T) {
	testSessionRPCBridgeCallJSONSupportsAllSessionRPCs(t)
}

func TestE2ELoaderEngineWorkflow(t *testing.T) {
	testLoaderEngineExecuteSupportsSessionRPCBindings(t)
	testLoaderEngineExecuteSupportsAgentAndLLMBindings(t)
	testLoaderEngineExecuteSupportsCommandBindings(t)
	TestLoaderEngineJSONAndRegistrationBranches(t)
}

func TestE2EServiceGraphRegistersV2Routes(t *testing.T) {
	testSupportSetupRegistersServiceGraph(t)
}

func TestE2EWebhookWorkspaceAndLoaderWorkflow(t *testing.T) {
	testConfigStoreMigrationAndTimeParsingWorkflows(t)
	testServiceConfigAndLoaderAPIs(t)
	testServiceSessionKernelAgentAndLLMAPIs(t)
	testServiceProxyRoutesRedirectAndProxy(t)
	TestServiceProxyRoutesUseGuestHostTarget(t)
	testServiceEnsureProxyReadyStartPaths(t)
	TestJupyterTargetReachableUsesGuestHostTarget(t)
	TestSessionDriverStartSessionVMSavesRuntimeProxyState(t)
	testServiceStreamingAPIs(t)
	testRuntimeProviderSelectsConfiguredRuntime(t)
	testLLMClientGenerateHandlesSuccessAndFailures(t)
	testWebhookHandlerStoresEvent(t)
	testEventQueryHandlers(t)
	testPrepareFileWorkspaceCopiesContent(t)
	testPrepareGitWorkspaceClonesRootAndTarget(t)
	testRegisterWorkspaceRoutesUploadAndList(t)
	testLoaderManagerCollectDueScheduledRunsConsumesTimeout(t)
	testLoaderRunHostCommandPersistsShellCellArtifactsAndEvents(t)
	TestLoaderRunHostCommandPersistsDockerProxyTarget(t)
	testLoaderRunHostCommandNonZeroExitCodeDoesNotThrow(t)
	testLoaderRunHostAgentStopsSessionAfterExecution(t)
	testLoaderRunCommandNewSessionsReuseAndCleanupAtRunEnd(t)
	TestLoaderRunCommandStickySessionPersistsAcrossRunsWithTitle(t)
	testLoaderManagerRunLifecycleStateLLMAndEventDispatch(t)
	testLoaderManagerDispatchScheduledRunsAndSessionResumeBranches(t)
	testLoaderScheduleModelWorkflows(t)
	testSupportConstructorsAndHelpers(t)
	testSupportControlPlaneStartAndConfigHelpers(t)
	testSupportSetupRegistersServiceGraph(t)
	testControlPlaneHelperErrorAndParsingBranches(t)
	TestModelSessionConfigAndBusBranchCoverage(t)
	TestTopicEventModelAndStoreErrorBranches(t)
	testServiceReconcilePersistedSessionsMarksStalePendingFailed(t)
	TestServiceAndBridgeReconcileMicrosandboxRuntimeTypeBranches(t)
	testStoreAgentRunLegacyVMAndListWorkflows(t)
	testStorePersistenceErrorAndUpdateBranches(t)
	testServiceProtoConversionHelpers(t)
	testAgentRunSummariesScansAllSessions(t)
	testAgentDefinitionConfigStoreCRUDAndWorkspaceProtection(t)
	testLoaderCreateBindsAgentDefinitionProvider(t)
	testAgentDefinitionValidationAndProtoMapping(t)
	testAgentDefinitionCreateSession(t)
	testDeleteAgentDefinitionStopsSessionsAndKeepsDeletedInList(t)
	testDashboardOverviewAggregatorCountsRuns(t)
	testDashboardOverviewHubWatchInitialAndNotify(t)
	testWebhookIntegrationEventDispatchRunsMatchingLoader(t)
}
